// <auto-generated />
namespace codefirstdemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class techersnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(techersnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070944389_techersnew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
